### ISSUE TITLE
TestIOPoll fails if os.TempDir is on a tmpfs

### ISSUE THREAD

**Issue by pktpls** [godzie44/go-uring#5]
Most often `os.TempDir()` is `/tmp`, which is often a `tmpfs` type mount, which doesn't support `O_DIRECT` file operations.

```
    ring_iopoll_test.go:127: 
        	Error Trace:	ring_iopoll_test.go:127
        	            				ring_iopoll_test.go:52
        	Error:      	Received unexpected error:
        	            	open /tmp/basic-rw2171370489: invalid argument
        	Test:       	TestIOPoll
--- FAIL: TestIOPoll (0.00s)
```

Sorry that I don't have a fix :-) But your code is very useful to read and learn from.

**Comment by godzie44** [comment]
I looked at similar tests in liburing and made sure that they also do not use /tmp. So replace /tmp to pwd looks fine. Thanks for issue!
