### ISSUE TITLE
panic: io_uring_setup: cannot allocate memory

### ISSUE THREAD

**Issue by Taron133** [godzie44/go-uring#7]
The file runs in Docker on Windows. But it crashes with an error in 
5.4 24 November 2019 20th LTS release, used in Ubuntu 20.04 LTS

```
# Build stage
FROM golang:1.22-alpine AS builder 
RUN apk add --no-cache wget
WORKDIR /build 
COPY / .
RUN go get -v && CGO_ENABLED=0 go build -v -o /build/authIO 
 
# Run stage
FROM alpine:latest AS production 
WORKDIR /build 
COPY --from=builder /build/authIO .
 
ARG PORT
EXPOSE 8080
CMD ["/build/authIO"]
```

From example:

```
func ringSrv(mux *http.ServeMux) {
	ringCnt := *ringCount

	var params []uring.SetupOption
	runtime.GOMAXPROCS(runtime.NumCPU() * 2)

	rings, stop, err := uring.CreateMany(ringCnt, uring.MaxEntries>>2, 1, params...)
	checkErr(err) // panic: io_uring_setup: cannot allocate memory
	defer stop() //nolint
```

**Comment by godzie44** [comment]
Hi, did you try to increase memlock limit in your container?

The error occurs inside a system call io_uring_setup, and, as i can see, you have not enough memory for your process. Try to increase it with `ulimit -l`

**Comment by godzie44** [comment]
I'll close this issue for now. Feel free to reopen when you've got more questions
